### PR TITLE
Added post-processing script functionality

### PR DESCRIPTION
**Pull request by djedi-knight**
a single script file can now be executed after movie files have been
moved/renamed.  The script is currently passed in one argument: the new
file path name.

### CODE REVIEW

**Comment by lgordon** [comment]
sweet, I've been wanting this! thanks!

can I give it an absolute path to the script?

**Comment by djedi-knight** [comment]
no, right now it's setup to look for the script in the CouchPotato install directory

**Comment by nickdima** [comment]
Can it be a bash script? or Python only?

**Comment by Dahlgren** [comment]
The file is executed as a separate process so it doesn't matter what type of script it is

**Pull request merged**
