### PR TITLE
Added support for notifications to Synology Media Server.

### PR DESCRIPTION
**Pull request by khellang**
This commit adds the option to send notifications to Synology Media Server. A great feature for us who run CP on a Synology NAS. I have wanted this feature for a long time because I basicly have to re-index the whole media library every time a new movie has been downloaded. Now CP does it for you :)

### CODE REVIEW

**Comment by RuudBurger** [comment]
You changed the return values of the renamer. This will bug out other functions after that I think. (not on a computer to test it).

**Comment by khellang** [comment]
First I tried with `finalDestination['filename']`, but it always returned the moviename with `.mkv` at the end, so it was wrong, thus unusable.
Because the notifier needs to add _all_ the files (if more than one), I changed the single `filename` to `filenames`, and included them in the returned array. I checked and couldn't find any other calls that would use the old returned `filename` from the `renameFiles`-method. All the others only uses `directory`

I have tested this commit with several movies and all of them were renamed right. The only thing I haven't gotten to test is movies with multiple cds/files.

**Comment by RuudBurger** [comment]
You are right.. must have been something from the old days ;)

**Comment by mreid-tt** [comment]
Just updated to version 3913d83 and noted the above new feature. I thought great! This will now work like Sick Beard sending notifications to the synoindex daemon! So I turned it on and rebooted the app but I get the following entries in the log:

INFO [ app.lib.synoindex] Executing synoindex command: ['/usr/syno/bin/synoindex', '-a', u'/volume1/video/Movies (720p-DTS)/Soul Surfer (2011)/Soul Surfer (2011).mkv']
INFO [ app.lib.synoindex] Result from synoindex: ('', None)

Is this normal? Did it add anything? I can't see the movie directory which was created via the renamer function earlier in XBMC. Usually I'd have to issue a reindex to see new directories which the renamer creates. Let me know if it's working for anyone else...

Versions: Synology DS410 with DSM 3.1-1748, CouchPotato 2.0 SPK (from http://synoblog.superzebulon.org/2011/05/couchpotato-2-0-spk/) with revision 3913d83 updated from the web interface.

**Comment by khellang** [comment]
I will have a look at it when I get home :)

**Comment by mreid-tt** [comment]
It appears that when creating new folders it does not appear in the index. I've also noticed the same thing when creating new shows in Sick Beard so it is not unique to CP. I'll post a similar bug report there so hopefully we can get to the bottom of this.

Versions: Synology DS410 with DSM 3.1-1748, CouchPotato 2.0 SPK (from http://synoblog.superzebulon.org/2011/05/couchpotato-2-0-spk/) with revision 666fd8b updated from the web interface.

**Comment by khellang** [comment]
I have also noticed the same behaviour with Sick Beard when creating a new folder. On CP you always create a new folder for each new movie, and thus never get it indexed. With synoindex you have separate commands for adding files and folders. I'll try to change the command to adding folders instead of files, and see if it works :)

**Pull request merged**
