### PR TITLE
Second attempt at XBMC MySQL support 

### PR DESCRIPTION
**Pull request by ghost**
Added the ability to use a centralized MySQL XBMC library database. 

As of the right now, if the connection fails, the user will not be alerted.  If the movie already exists in the library, the user won't be alerted and the movie won't be added to the queue.  

I have kept the ability to check in either the SQLite local database or connect to a MySQL server hosted library.  The setup can be found on the Extras tab, as I did not feel it made sense for this to be under Notifications.

### CODE REVIEW

**Comment by ghost** [comment]
Created this second pull request, because my first fork got screwed up.  Now I know not to make changes to a branch I am trying to get pulled ;)

**Comment by ghost** [comment]
Is there anything I can do to get this request pulled?  If nobody wants it, I can just go ahead and close it.

**Comment by frotsen** [comment]
Well this is a feature i very mutch like to se commited.

**Comment by neoflex** [comment]
yep, me too

**Comment by johoja12** [comment]
Me too, would love this.

**Comment by ouranos** [comment]
Is it still needed now that we can do it via the web api ?

See https://github.com/RuudBurger/CouchPotato/pull/411

**Comment by frotsen** [comment]
Ofcourse it is, many of os have a dedicated server that has sabnzb,sickbeard,couchpotato, mysql installed. Use of xbmc web api is nice nice but xmbc has to be running, Mysql support is the best way to do this, cause then we dont have to have xbmc running 24/7

**Comment by bonega** [comment]
Mysql support would be nice, but there is a problem.

I don't think the xbmc-developers consider mysql a public interface.
They will probably break compability more often than for json-rpc.

Perhaps somebody should ask the xbmc-developers what their vision is for mysql and external tools.
Mysql integration would be most appreciated.

**Comment by mvanderberg** [comment]
@putneyj 

Hi,

I was wondering if you are still using this?
Checked the xbmc fora, but there doesn't seem to be a two tier (client/server like Plex) solution in the pipeline soon.
The functionality to update the central mysql database could be handy as more people are using multiple xbmc boxes in the house as thing like the ATV2 and rhe Raspberry PI get cheaper..

Thanks in advance,
best regards, Mark
ps. I checked the notifications tab, but for XBMC I only see the DB path, but nothing to connect to a mysql instance..

**Comment by schumi2004** [comment]
Is this Frodo compatible ?

And maybe ported to the server version of CP ?

**Pull request closed without merging**
