### PR TITLE
Added support for downloading NZBs with NZBget

### PR DESCRIPTION
**Pull request by khellang**
Tested and works perfectly on both my pc and nas :)

### CODE REVIEW

**Comment by RuudBurger** [comment]
Is that the default password or something? Or should this be empty?

**Comment by khellang** [comment]
That is the default password, it's left there intentionally

**Comment by RuudBurger** [comment]
Ok cool.
Thanks for al the work ;)

**Comment by khellang** [comment]
No problem! I have been wanting nzbget and twitter support for a long time, so I figured i'd just write it myself :)

**Pull request merged**
