### PR TITLE
Handy function for all providers that do not have imdb info in their uploads!

### PR DESCRIPTION
**Pull request by nls44**
If a release name does not contain a year this will call the API of nzb.su and see if this
release name matches up to the proper imdb id. I've added this to base.py since it might be
useful for other providers (in the future possibly) that don't have the means to get imdb
information and since it is only necessary if the release name does not contain a year.
- added new provider (SceneAccess)
- added new provider (#alt.binaries.moovee on EFnet)

### CODE REVIEW

**Comment by nls44** [comment]
Sorry Ruud, forgot something small, added a fix for it.

**Comment by nls44** [comment]
I'll be finishing up on the bus and train haha. Committed it to have access on my server but forgot it updated the pull req too :(

**Comment by nls44** [comment]
Good to go :D

**Comment by mr-bo-jangles** [comment]
really really love the SCC provider :DDDD please let this be pulled ASAP! :D

**Comment by jameswyse** [comment]
Nice!

**Pull request closed without merging**
