### PR TITLE
Mobile theme / webapp

### PR DESCRIPTION
**Pull request by nvaken**
Living in the era of smart phones, I thought it would be time to make Couchpotato a bit better compatible with mobile phones. That's why I've created this responsive CSS stylesheet. Since this stylesheet does actually remove some functionalities (which I ought to be non-important on a mobile device) I've included a option to enable the CSS, which is by default "False".

Features: 
- Optional enabling the "webapp".
- Loading screen on Apple touch devices.
- Less is more, especially on mobile devices; no options and such. 

First time on python for me and also on forking a git repo, might be wise to check out my attempts on those... Also, I did not make this styling to make it a "beautiful" webapp, but just to make it function better.

### CODE REVIEW

**Comment by nvaken** [comment]
Oh, hold your horses, I've left out a bit of critical JS. Just one moment please.

**Comment by nvaken** [comment]
Okay, done. Go go go go!

**Comment by RuudBurger** [comment]
Cool that you are trying to help! The bad thing is, I won't do anymore work to v1, please check out CouchPotatoServer ;)

**Comment by nvaken** [comment]
Roger that! No problem. :) Heard some noise about V2, but everything I read about it was pretty vague and I've seen CouchPotatoServer within your repo's. Wasn't really sure about that package, I'll check it out for sure though.

Thanks!

**Pull request closed without merging**
