### PR TITLE
initial commit for --datadir and --config support

### PR DESCRIPTION
**Pull request by travisghansen**
This adds support for 2 cli options
--config
--datadir

--datadir attempts (and achieves I believe) to keep all app created data out of the source directory.
--config allow for pointing to a custom location for the config file

Thanks for the consideration!

### CODE REVIEW

**Comment by RuudBurger** [comment]
Thanks, will have a look when I have the time. Seperate dir for the config would be kinda useless though. Just pointing it to a data dir seems to be enough.

**Comment by travisghansen** [comment]
There are a couple of cases when --config makes sense..
1. unix init scripts where generally speaking config files are stored in /etc/<app> but data stays in /var/lib/<app>
2. with xbmc add-on wrapper around cp we'll need/want the data and config files in separate places as well

Again thanks for the consideration, I know work has already started on v2 but v1 is what's getting included in the openelec builds for now.

**Comment by RuudBurger** [comment]
Ok, cool! (what do I know, right?)

**Comment by travisghansen** [comment]
Thanks!

**Pull request merged**
