### PR TITLE
Added ability to use web API against XBMC to determine if movie exists

### PR DESCRIPTION
**Pull request by cancan101**
Rather than using the flat file database, added the ability to use the web api for couch potato to contact XBMC and see if movie is already in user's database.

Currently it queries all XBMC and if any has movie then download is skipped.

### CODE REVIEW

**Comment by RuudBurger** [comment]
Thanks!

**Comment by KruyKaze** [comment]
I updated but I don't see how to enable this.

**Comment by cancan101** [comment]
Right now this feature is enabled by default if you have any XBMC hosts listed in your config,
I plan to add a config check-box to allow turning on/off this check (I need to learn about the config modules).

Another feature that I want to add is a quality check. Right now (using the flat database file or this new API check), if I attempt to add a movie that exists even if the new request is for a version of higher quality, the movie will be skipped. I am looking into addressing this issue.

**Comment by KruyKaze** [comment]
Does XBMC have to be running at the time when you're adding that movie or does it check periodically ?
Thanks

**Comment by cancan101** [comment]
XBMC does need to be running when the movie is added.

**Comment by KruyKaze** [comment]
Nice thank you

On Thu, Dec 29, 2011 at 9:59 PM, cancan101
reply@reply.github.com
wrote:

**Pull request merged**
