### PR TITLE
New line was missing in the PID file

### PR DESCRIPTION
**Pull request by Jeroenve**

### CODE REVIEW

**Comment by RuudBurger** [comment]
What is this for?

**Comment by Jeroenve** [comment]
```
DiskStation> cat /tmp/mysqld.pid
6513
DiskStation> cat /tmp/postgresql.pid
4249
DiskStation> cat /volume1/@appstore/.couchpotato/couchpotato.pid
16749DiskStation>
```

Every pid file ends with a new line except CouchPotato.

**Comment by RuudBurger** [comment]
And you are having problems with this? Works like everything else for me ;)
Not going to change cherrypy files. If it's a bug, I suggest you tell them, so others can enjoy the fix also.

Thanks!

**Comment by Jeroenve** [comment]
Reported it.
https://bitbucket.org/cherrypy/cherrypy/issue/1116/new-line-missing-at-pid-file

**Pull request closed without merging**
