### PR TITLE
Notify my android

### PR DESCRIPTION
**Pull request by itsmegb**
Added support for NotifyMyAndroid

### CODE REVIEW

**Comment by RuudBurger** [comment]
Assuming this works.
Living on the edge today ;)

**Comment by itsmegb** [comment]
ive been using it the last few days, appears to be pretty stable. i fixed the only error i came across!

**Comment by ghost** [comment]
NMA? Gotta get refererences for it to include it futher in ANY OF MY projects.

Edit: tagged it for personal reasons ;)

**Comment by itsmegb** [comment]
what do you mean nightspirit81?

**Comment by ghost** [comment]
Never heard of it, tagged it to look into it when I have some time ;)

**Comment by itsmegb** [comment]
ahh i get you, my next task is Sick-Beard integration :D

**Pull request merged**
