### PR TITLE
Added ETA check to searchAll query

### PR DESCRIPTION
**Pull request by CyberJack**
I added an ETA check (theater and dvd) to the query searchAll function.

Now if an ETA is known and has not passed the movie will not be searched for.
If no ETA is available the movies will still be searched

This saves a lot of unnecessary api calls and the total processing time when searching for all movies will decrease.

### CODE REVIEW

**Comment by MysticSpirit** [comment]
I would like to see this pull request granted. It saves time and API requests wich is good for load on all used services and CP itself.

**Comment by rinkeb** [comment]
+1

**Comment by RuudBurger** [comment]
https://github.com/CyberJack/CouchPotato/blob/43584e585b350b24ce9070b87a53111b8f73206a/app/lib/cron/yarr.py#L113-L135 ;)

**Comment by RuudBurger** [comment]
You know this repo is for the old version right?

**Comment by CyberJack** [comment]
Right, I know.
I just closed a old pull request which was still open.

**Pull request closed without merging**
