### PR TITLE
Kere.ws

### PR DESCRIPTION
**Pull request by pheelee**
I've added a new NZB Indexer (kere.ws) specially for German releases.

### CODE REVIEW

**Comment by w00dst0ck** [comment]
DANKE!

Please add it also to CouchPotatoServer.

Best regards,
w00dst0ck

**Comment by RuudBurger** [comment]
What he said ;)

**Comment by RuudBurger** [comment]
No I was referring to "please add it also to CouchPotatoServer" part.
You don't need to tell me what danke mean ;)

**Comment by pheelee** [comment]
On my way.. ;)

**Pull request closed without merging**
