### PR TITLE
Implemented support for NotifyMyWindowsPhone

### PR DESCRIPTION
**Pull request by yngvebn**
Notifications can be sent to NotifyMyWindowsPhone when movies are snatched.. Much like NMA and Notifo, but for Windows Phone 7.5

### CODE REVIEW

**Comment by RuudBurger** [comment]
Ow nice. You don't mind that I use this for v2 right?

**Comment by yngvebn** [comment]
You're free to use it for whatever you want :) I'm just happy you accepted my pull request (it's my first ever on github :D)

**Comment by RuudBurger** [comment]
Thanks ;)
https://github.com/RuudBurger/CouchPotatoServer/commit/d2fd098030e605c6672f23053b70ae2c3128df6d

**Comment by yngvebn** [comment]
Excellent! When do you expect the new version to be released? How's the API-support? I'm wondering about making a WP7 app for Couch/Sab/SickBeard...

**Pull request merged**
